name: flutter_clean_arc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.0.3+1 
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true