name: flutter_clean_arc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.5

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.0.3+1 
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  faker: 2.0.0
  http_mock_adapter: ^0.3.3
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#004d9a"

flutter:
  uses-material-design: true